# Generated by Django 5.1.5 on 2025-03-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('num_courses', models.IntegerField(default=0)),
            ],
        ),
    ]
